#include "ch1116.h"

#include <string.h>

#include "driver/gpio.h"
#include "driver/i2c.h"
#include "esp_err.h"
#include "esp_log.h"
#include "font8x8_basic.h"
#include "freertos/task.h"
#include "sdkconfig.h"  // generated by "make menuconfig"

#define SDA_PIN GPIO_NUM_4
#define SCL_PIN GPIO_NUM_5

#define tag "ch1116"

void i2c_master_init() {
  i2c_config_t i2c_config = {.mode = I2C_MODE_MASTER,
                             .sda_io_num = SDA_PIN,
                             .scl_io_num = SCL_PIN,
                             .sda_pullup_en = GPIO_PULLUP_ENABLE,
                             .scl_pullup_en = GPIO_PULLUP_ENABLE,
                             .master.clk_speed = 1000000};
  i2c_param_config(I2C_NUM_0, &i2c_config);
  i2c_driver_install(I2C_NUM_0, I2C_MODE_MASTER, 0, 0, 0);
}

void ch1116_init() {
  esp_err_t espRc;

  i2c_cmd_handle_t cmd = i2c_cmd_link_create();

  i2c_master_start(cmd);
  i2c_master_write_byte(cmd, (CH1116_ADDRESS << 1) | I2C_MASTER_WRITE, true);

  i2c_master_write_byte(cmd, CH1116_CONTROL_BYTE_COMMAND_STREAM, true);

  i2c_master_write_byte(cmd, CH1116_DISPLAY_OFF, true);

  i2c_master_write_byte(cmd, CH1116_LOWER_COLUMN_ADDRESS, true);
  i2c_master_write_byte(cmd, CH1116_HIGHER_COLUMN_ADDRESS, true);

  i2c_master_write_byte(cmd, CH1116_DISPLAY_START_LINE, true);

  i2c_master_write_byte(cmd, CH1116_PAGE_ADDRESS, true);

  i2c_master_write_byte(cmd, CH1116_CONTRACT_CONTROL, true);
  i2c_master_write_byte(cmd, CH1116_CONTRACT_CONTROL_128, true);

  i2c_master_write_byte(cmd, CH1116_SEGMENT_REMAP, true);

  i2c_master_write_byte(cmd, CH1116_NORMAL_DISPLAY, true);

  i2c_master_write_byte(cmd, CH1116_MULTIPLEX_RATIO, true);
  i2c_master_write_byte(cmd, CH1116_MULTIPLEX_RATIO_1_64, true);

  i2c_master_write_byte(cmd, CH1116_CHARGE_PUMP_ENABLE, true);
  i2c_master_write_byte(cmd, CH1116_CHARGE_PUMP_ENABLE_INTERNAL_VCC, true);

  i2c_master_write_byte(cmd, CH1116_CHARGE_PUMP_VOLTAGE_9V, true);

  i2c_master_write_byte(cmd, CH1116_COM_SCAN_DIRECTION, true);

  i2c_master_write_byte(cmd, CH1116_DISPLAY_OFFSET, true);
  i2c_master_write_byte(cmd, CH1116_DISPLAY_OFFSET_0, true);

  i2c_master_write_byte(cmd, CH1116_SET_OSC_DIVISION, true);
  i2c_master_write_byte(cmd, CH1116_SET_OSC_DIVISION_1, true);

  i2c_master_write_byte(cmd, CH1116_SET_PRE_CHARGE_PERIOD, true);
  i2c_master_write_byte(cmd, CH1116_SET_PRE_CHARGE_PERIOD_1, true);

  i2c_master_write_byte(cmd, CH1116_SET_COM_PINS, true);
  i2c_master_write_byte(cmd, CH1116_SET_COM_PINS_1, true);

  i2c_master_write_byte(cmd, CH1116_SET_VCOMH, true);
  i2c_master_write_byte(cmd, CH1116_SET_VCOMH_1, true);

  i2c_master_write_byte(cmd, CH1116_DISPLAY_ON, true);

  i2c_master_stop(cmd);

  espRc = i2c_master_cmd_begin(I2C_NUM_0, cmd, 10 / portTICK_PERIOD_MS);
  if (espRc == ESP_OK) {
    ESP_LOGI(tag, "OLED configured successfully");
  } else {
    ESP_LOGE(tag, "OLED configuration failed. code: %s",
             esp_err_to_name(espRc));
  }
  i2c_cmd_link_delete(cmd);
}

void task_ch1116_display_pattern(void *ignore) {
  i2c_cmd_handle_t cmd;

  for (uint8_t i = 0; i < 8; i++) {
    cmd = i2c_cmd_link_create();
    i2c_master_start(cmd);
    i2c_master_write_byte(cmd, (CH1116_ADDRESS << 1) | I2C_MASTER_WRITE, true);
    i2c_master_write_byte(cmd, CH1116_CONTROL_BYTE_COMMAND_SINGLE, true);
    i2c_master_write_byte(cmd, 0xB0 | i, true);
    i2c_master_write_byte(cmd, CH1116_CONTROL_BYTE_DATA_STREAM, true);
    for (uint8_t j = 0; j < 132; j++) {
      i2c_master_write_byte(cmd, 0xFF >> (j % 8), true);
    }
    i2c_master_stop(cmd);
    i2c_master_cmd_begin(I2C_NUM_0, cmd, 10 / portTICK_PERIOD_MS);
    i2c_cmd_link_delete(cmd);
  }
}

void task_ch1116_display_clear(void *ignore) {
  i2c_cmd_handle_t cmd;

  uint8_t zero[132];
  memset(zero, 0, 132);
  for (uint8_t i = 0; i < 8; i++) {
    cmd = i2c_cmd_link_create();
    i2c_master_start(cmd);
    i2c_master_write_byte(cmd, (CH1116_ADDRESS << 1) | I2C_MASTER_WRITE, true);
    i2c_master_write_byte(cmd, CH1116_CONTROL_BYTE_COMMAND_SINGLE, true);
    i2c_master_write_byte(cmd, 0xB0 | i, true);

    i2c_master_write_byte(cmd, CH1116_CONTROL_BYTE_DATA_STREAM, true);
    i2c_master_write(cmd, zero, 132, true);
    i2c_master_stop(cmd);
    i2c_master_cmd_begin(I2C_NUM_0, cmd, 10 / portTICK_PERIOD_MS);
    i2c_cmd_link_delete(cmd);
  }

  cmd = i2c_cmd_link_create();
  i2c_master_start(cmd);
  i2c_master_write_byte(cmd, CH1116_CONTROL_BYTE_COMMAND_STREAM, true);
  i2c_master_write_byte(cmd, 0x00, true);  // reset column
  i2c_master_write_byte(cmd, 0x10, true);
  i2c_master_write_byte(cmd, 0xB0, true);  // reset page
  i2c_master_stop(cmd);
  i2c_master_cmd_begin(I2C_NUM_0, cmd, 10 / portTICK_PERIOD_MS);
  i2c_cmd_link_delete(cmd);
}

void task_ch1116_contrast(void *ignore) {
  i2c_cmd_handle_t cmd;

  uint8_t contrast = 0;
  uint8_t direction = 1;
  while (true) {
    cmd = i2c_cmd_link_create();
    i2c_master_start(cmd);
    i2c_master_write_byte(cmd, (CH1116_ADDRESS << 1) | I2C_MASTER_WRITE, true);
    i2c_master_write_byte(cmd, CH1116_CONTROL_BYTE_COMMAND_STREAM, true);
    i2c_master_write_byte(cmd, CH1116_CONTRACT_CONTROL, true);
    i2c_master_write_byte(cmd, contrast, true);
    i2c_master_stop(cmd);
    i2c_master_cmd_begin(I2C_NUM_0, cmd, 10 / portTICK_PERIOD_MS);
    i2c_cmd_link_delete(cmd);
    vTaskDelay(1 / portTICK_PERIOD_MS);

    contrast += direction;
    if (contrast == 0xFF) {
      direction = -1;
    }
    if (contrast == 0x0) {
      direction = 1;
    }
  }
  vTaskDelete(NULL);
}

void task_ch1116_display_text(const void *arg_text) {
  char *text = (char *)arg_text;
  uint8_t text_len = strlen(text);

  i2c_cmd_handle_t cmd;

  uint8_t cur_page = 0;

  cmd = i2c_cmd_link_create();
  i2c_master_start(cmd);
  i2c_master_write_byte(cmd, (CH1116_ADDRESS << 1) | I2C_MASTER_WRITE, true);

  i2c_master_write_byte(cmd, CH1116_CONTROL_BYTE_COMMAND_STREAM, true);
  i2c_master_write_byte(cmd, 0x08, true);  // reset column
  i2c_master_write_byte(cmd, 0x10, true);
  i2c_master_write_byte(cmd, 0xB0 | cur_page, true);  // reset page

  i2c_master_stop(cmd);
  i2c_master_cmd_begin(I2C_NUM_0, cmd, 10 / portTICK_PERIOD_MS);
  i2c_cmd_link_delete(cmd);

  for (uint8_t i = 0; i < text_len; i++) {
    if (text[i] == '\n') {
      cmd = i2c_cmd_link_create();
      i2c_master_start(cmd);
      i2c_master_write_byte(cmd, (CH1116_ADDRESS << 1) | I2C_MASTER_WRITE,
                            true);

      i2c_master_write_byte(cmd, CH1116_CONTROL_BYTE_COMMAND_STREAM, true);
      i2c_master_write_byte(cmd, 0x08, true);  // reset column
      i2c_master_write_byte(cmd, 0x10, true);
      i2c_master_write_byte(cmd, 0xB0 | ++cur_page, true);  // increment page

      i2c_master_stop(cmd);
      i2c_master_cmd_begin(I2C_NUM_0, cmd, 10 / portTICK_PERIOD_MS);
      i2c_cmd_link_delete(cmd);
    } else {
      cmd = i2c_cmd_link_create();
      i2c_master_start(cmd);
      i2c_master_write_byte(cmd, (CH1116_ADDRESS << 1) | I2C_MASTER_WRITE,
                            true);

      i2c_master_write_byte(cmd, CH1116_CONTROL_BYTE_DATA_STREAM, true);
      i2c_master_write(cmd, font8x8_basic_tr[(uint8_t)text[i]], 8, true);

      i2c_master_stop(cmd);
      i2c_master_cmd_begin(I2C_NUM_0, cmd, 10 / portTICK_PERIOD_MS);
      i2c_cmd_link_delete(cmd);
    }
  }
}

void ch1116_main(void) {
  i2c_master_init();
  ch1116_init();

  task_ch1116_display_pattern(NULL);
  vTaskDelay(1000 / portTICK_PERIOD_MS);
  task_ch1116_display_clear(NULL);
  task_ch1116_display_text("Hello!\nMultiline OK!\nAnother line.");
  xTaskCreate(&task_ch1116_contrast, "ssid1306_contrast", 2048, NULL, 6, NULL);
}